---
site_name: 42picky
site_url: https://42picky.readthedocs.io/
repo_url: https://github.com/42picky/42picky.github.io
edit_uri: https://github.com/42picky/42picky.github.io/blob/main/docs/
copyright: Copyright &copy; Sorin Sbarnea
strict: true

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - content.action.edit
    - navigation.sections
    # - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: amber
      accent: "deep orange"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: "deep orange"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/42picky/42picky.github.io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/42picky
# nav:
#   - home: index.md

plugins:
  - search
  - autorefs
  - social
  - markdown-exec
  - mkdocstrings
  - git-authors:
      exclude:
        - index.md
        - tags.md
  - tags:
      # tags_hierarchy: true

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        # markdown_exec adds its own dynamically
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
